name: Snyk Security Scan

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  snyk:
    name: Snyk Scan
    runs-on: ubuntu-latest

    permissions:
      contents: read
      security-events: write
      actions: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies (auto)
        run: |
          find . -name package.json -not -path "*/node_modules/*" -execdir npm install --legacy-peer-deps \;

      - name: Install Snyk CLI
        uses: snyk/actions/setup@master

      - name: Authenticate with Snyk
        run: snyk auth ${{ secrets.SNYK_TOKEN }}

      # -----------------------------
      # Run dependency scan once for entire repo
      # -----------------------------
      - name: Snyk dependency scan (JSON output)
        run: snyk test --all-projects --json-file-output=deps.json
        continue-on-error: true

      # -----------------------------
      # Run Snyk Code scan once for entire repo
      # -----------------------------
      - name: Snyk Code (SAST) scan (JSON output)
        run: snyk code test --all-projects --json-file-output=code.json || true

      # -----------------------------
      # Generate HTML reports
      # -----------------------------
      - name: Generate HTML reports
        run: |
          npm install -g snyk-to-html
          mkdir -p snyk-report

          if [ -f deps.json ]; then
            snyk-to-html -i deps.json -o snyk-report/deps-report.html
          else
            echo "⚠️ No dependency JSON found."
          fi

          if [ -f code.json ]; then
            snyk-to-html -i code.json -o snyk-report/code-report.html
          else
            echo "⚠️ No code JSON found."
          fi
        shell: bash
        continue-on-error: true

      # -----------------------------
      # Upload combined reports as single artifact
      # -----------------------------
      - name: Upload Snyk HTML reports
        uses: actions/upload-artifact@v4
        with:
          name: snyk-full-report
          path: snyk-report

      # -----------------------------
      # Fail PR if high/critical issues exist
      # -----------------------------
      - name: Fail PR on high/critical issues
        run: |
          # Count high/critical vulnerabilities in dependencies
          DEPS_HIGH=$(jq '[.vulnerabilities[] | select(.severity=="high" or .severity=="critical")] | length' deps.json || echo 0)
          # Count high/critical issues in code scan
          CODE_HIGH=$(jq '[.issues[] | select(.severity=="high" or .severity=="critical")] | length' code.json || echo 0)
          TOTAL=$((DEPS_HIGH + CODE_HIGH))

          if [ "$TOTAL" -gt 0 ]; then
            echo "❌ Found $TOTAL High/Critical vulnerabilities/issues. Blocking PR!"
            exit 1
          else
            echo "✅ No High/Critical issues found. PR can be merged."
          fi
        shell: bash
